application/models/__init__.py
from ._base import db
from .user import *
from .piece import *
from .collection import *
from .notification import *
from .feedback import *
from .log import *

application/models/_base.py
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

application/forms/__init__.py
from .account import *
from .piece import *
from .user import *
from .collection import *
from .feedback import *
from .admin import *

application/forms/_helper.py
# coding: utf-8
import re
from urlparse import urlparse


def check_url(form, field):
    """检查url schema，若不存在则默认补充http"""
    url = field.data.strip()
    if not url:
        return
    result = urlparse(url)
    if result.scheme == "":
        field.data = "http://%s" % re.sub(r'^:?/*', '', url)


def trim(form, field):
    if field.data and isinstance(field.data, basestring):
        field.data = field.data.strip()

application/forms/admin.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired, Email


class SendInvitationCodeForm(Form):
    email = StringField('邮箱', validators=[
        DataRequired('邮箱不能为空'),
        Email('邮箱格式不正确')
    ])

application/forms/collection.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired, Optional


class CollectionForm(Form):
    title = StringField('名称', validators=[DataRequired('句集名称不能为空')])
    desc = StringField('描述')
    kind_id = SelectField('类型', validators=[Optional()], coerce=int)

application/forms/feedback.py
# coding: utf-8
from flask_wtf import Form
from wtforms import TextAreaField
from wtforms.validators import DataRequired


class FeedbackForm(Form):
    content = TextAreaField('反馈内容',
                            validators=[DataRequired('反馈内容不能为空')],
                            description="我是壹经典的开发者 hustlzp，把你遇到的问题，或是想要的功能告诉我吧")

application/forms/piece.py
# coding: utf-8
import re
import math
from flask_wtf import Form
from wtforms import StringField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, URL, Optional
from ._helper import check_url, trim
from ..models import Piece


class PieceForm(Form):
    content = TextAreaField('句子', validators=[DataRequired('句子不能为空'), trim])
    original = BooleanField('原创', default=False)
    author = StringField('原作者', validators=[Optional(), trim], description='选填')
    source = StringField('出处', validators=[Optional(), trim])
    source_link = StringField('链接',
                              validators=[Optional(), trim, check_url, URL(message='链接格式不正确')],
                              description='选填')
    comment = TextAreaField('附言',
                            validators=[Optional(), trim],
                            description='选填，个人感想或推荐理由')

    def validate_content(self, field):
        content = self.content.data
        content = content.strip()  # 去除首尾的空格
        content = re.sub('\r\n', '', content)  # 去掉换行符
        content = re.sub('\s+', ' ', content)  # 将多个空格替换为单个空格
        self.content.data = content

        content_length = Piece.calculate_content_length(self.content.data)
        if content_length > 200:
            raise ValueError('不超过200字')


class PieceCommentForm(Form):
    content = TextAreaField('评论',
                            validators=[DataRequired('评论内容不能为空')],
                            description='评论内容')

application/__init__.py
# coding: utf-8
import sys
import os

# Insert project root path to sys.path
project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_path not in sys.path:
    sys.path.insert(0, project_path)

import hashlib
import time
from flask import Flask, request, url_for, g, render_template
from flask_wtf.csrf import CsrfProtect
from flask.ext.uploads import configure_uploads
from flask_debugtoolbar import DebugToolbarExtension
from werkzeug.wsgi import SharedDataMiddleware
from werkzeug.contrib.fixers import ProxyFix
from .utils.account import get_current_user
from .utils.assets import register_assets
from config import load_config

# convert python's encoding to utf8
reload(sys)
sys.setdefaultencoding('utf8')


def create_app():
    """Create Flask app."""
    app = Flask(__name__)

    config = load_config()
    app.config.from_object(config)

    if not hasattr(app, 'production'):
        app.production = not app.debug and not app.testing

    # Proxy fix
    app.wsgi_app = ProxyFix(app.wsgi_app)

    # CSRF protect
    CsrfProtect(app)

    # Enable Sentry in production mode
    if app.production:
        from .utils.sentry import sentry

        sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))
    else:
        DebugToolbarExtension(app)

        # Serve static files during development
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/uploads': os.path.join(app.config.get('PROJECT_PATH'), 'uploads')
        })

    # Register components
    register_db(app)
    register_routes(app)
    register_jinja(app)
    register_assets(app)
    register_error_handle(app)
    register_uploadsets(app)
    register_hooks(app)

    return app


def register_jinja(app):
    """Register jinja filters, vars, functions."""
    from .utils import filters, permissions, helpers
    from .models import Notification, NOTIFICATION_KIND, PIECE_EDIT_KIND, COLLECTION_EDIT_KIND

    app.jinja_env.filters.update({
        'timesince': filters.timesince,
        'markdown': filters.markdown
    })

    @app.context_processor
    def inject_vars():
        return dict(
            notifications_count=g.user.notifications.filter(
                ~Notification.checked).count() if g.user else 0
        )

    def url_for_other_page(page):
        """Generate url for pagination."""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)

    rules = {}
    for endpoint, _rules in app.url_map._rules_by_endpoint.iteritems():
        if any(item in endpoint for item in ['_debug_toolbar', 'debugtoolbar', 'static']):
            continue
        rules[endpoint] = [{'rule': rule.rule} for rule in _rules]

    app.jinja_env.globals.update({
        'absolute_url_for': helpers.absolute_url_for,
        'url_for_other_page': url_for_other_page,
        'rules': rules,
        'permissions': permissions,
        'NOTIFICATION_KIND': NOTIFICATION_KIND,
        'PIECE_EDIT_KIND': PIECE_EDIT_KIND,
        'COLLECTION_EDIT_KIND': COLLECTION_EDIT_KIND
    })


def register_db(app):
    """Register models."""
    from .models import db

    db.init_app(app)


def register_routes(app):
    """Register routes."""
    from .controllers import site, account, piece, user, collection, feedback, admin

    app.register_blueprint(site.bp)
    app.register_blueprint(account.bp)
    app.register_blueprint(piece.bp)
    app.register_blueprint(user.bp)
    app.register_blueprint(collection.bp)
    app.register_blueprint(feedback.bp)
    app.register_blueprint(admin.bp)


def register_error_handle(app):
    """Register HTTP error pages."""

    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_uploadsets(app):
    """Register UploadSets."""
    from .utils.uploadsets import avatars, collection_covers, qrcodes

    configure_uploads(app, (avatars, collection_covers, qrcodes))


def register_hooks(app):
    """Register hooks."""

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user and g.user.is_admin:
            g._before_request_time = time.time()

    @app.after_request
    def after_request(response):
        if hasattr(g, '_before_request_time'):
            delta = time.time() - g._before_request_time
            response.headers['X-Render-Time'] = delta * 1000
        return response


def _get_template_name(template_reference):
    """Get current template name."""
    return template_reference._TemplateReference__context.name

application/controllers/account.py
# coding: utf-8
from flask import render_template, Blueprint, redirect, request, url_for, flash
from ..forms import SigninForm, SignupForm, ResetPasswordForm, ForgotPasswordForm
from ..utils.account import signin_user, signout_user
from ..utils.permissions import VisitorPermission
from ..utils.mail import send_activate_mail, send_reset_password_mail
from ..utils.security import decode
from ..utils.helpers import get_domain_from_email
from ..models import db, User, InvitationCode

bp = Blueprint('account', __name__)


@bp.route('/signin', methods=['GET', 'POST'])
@VisitorPermission()
def signin():
    """Signin"""
    form = SigninForm()
    referer = request.form.get('referer')
    if form.validate_on_submit():
        signin_user(form.user)
        return redirect(referer or url_for('site.index'))
    return render_template('account/signin.html', form=form)


@bp.route('/signup', methods=['GET', 'POST'])
@VisitorPermission()
def signup():
    """Signup"""
    form = SignupForm()
    code_string = request.args.get('code')
    if code_string:
        form.code.data = code_string
        code = InvitationCode.query.filter(InvitationCode.code == code_string).first()
        if code and code.email:
            form.email.data = code.email

    if form.validate_on_submit():
        user = User(name=form.name.data, email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        code = InvitationCode.query.filter(InvitationCode.code == form.code.data).first_or_404()
        code.used = True
        code.user_id = user.id
        db.session.add(code)
        db.session.commit()

        # 若用户填写的邮箱和code中的邮箱相同，则无需填写
        if user.email == code.email:
            user.is_active = True
            db.session.add(user)
            db.session.commit()
            signin_user(user)
            flash('注册成功，欢迎来到壹经典。')
            return redirect(url_for('site.index'))
        else:
            send_activate_mail(user)
            email_domain = get_domain_from_email(user.email)
            if email_domain:
                message = "请 <a href='%s' target='_blank'>登录邮箱</a> 激活账号" % email_domain
            else:
                message = "请登录邮箱激活账号"
            return render_template('site/message.html', title='注册成功', message=message)
    return render_template('account/signup.html', form=form)


@bp.route('/activate')
def activate():
    """激活账号"""
    token = request.args.get('token')
    if not token:
        return render_template('site/message.html', title="账号激活失败", message='无效的激活链接')

    user_id = decode(token)
    if not user_id:
        return render_template('site/message.html', title="账号激活失败", message='无效的激活链接')

    user = User.query.filter(User.id == user_id).first()
    if not user:
        return render_template('site/message.html', title="账号激活失败", message='无效的账号')

    user.is_active = True
    db.session.add(user)
    db.session.commit()
    signin_user(user)
    flash('账号激活成功，欢迎来到壹经典。')
    return redirect(url_for('site.index'))


@bp.route('/signout')
def signout():
    """Signout"""
    signout_user()
    return redirect(request.referrer or url_for('site.index'))


@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """忘记密码"""
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()

        if not user.is_active:
            return render_template('site/message.html', title="提示", message='请先完成账号激活')
        send_reset_password_mail(user)

        email_domain = get_domain_from_email(user.email)
        if email_domain:
            message = "请 <a href='%s' target='_blank'>登录邮箱</a> 完成密码重置" % email_domain
        else:
            message = "请登录邮箱完成密码重置"
        return render_template('site/message.html',
                               title="发送成功",
                               message=message)
    return render_template('account/forgot_password.html', form=form)


@bp.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    token = request.args.get('token')
    if not token:
        return render_template('site/message.html', title="密码重置失败", message='无效的密码重置链接')

    user_id = decode(token)
    if not user_id:
        return render_template('site/message.html', title="密码重置失败", message='无效的密码重置链接')

    user = User.query.filter(User.id == user_id).first()
    if not user or not user.is_active:
        return render_template('site/message.html', title="密码重置失败", message='无效的用户')

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = form.new_password.data
        db.session.add(user)
        db.session.commit()
        flash('密码重置成功，请使用新密码登录账户')
        return redirect(url_for('.signin'))
    return render_template('account/reset_password.html', form=form)

application/controllers/admin.py
# coding: utf-8
import datetime
from werkzeug.security import gen_salt
from flask import render_template, Blueprint, redirect, request, url_for, flash, g
from ..utils.permissions import AdminPermission
from ..utils.mail import send_invitation_mail
from ..forms import SendInvitationCodeForm
from ..models import db, CollectionEditLogReport, PieceEditLogReport, Feedback, InvitationCode, \
    User, Piece, Collection

bp = Blueprint('admin', __name__)


@bp.route('/admin/dashboard')
@AdminPermission()
def dashboard():
    today = datetime.date.today()
    today_users_count = User.query.filter(
        db.func.date(User.created_at) == today).count()
    today_pieces_count = Piece.query.filter(
        db.func.date(Piece.created_at) == today).count()
    today_collections_count = Collection.query.filter(
        db.func.date(Collection.created_at) == today).count()
    return render_template('admin/dashboard.html', today_users_count=today_users_count,
                           today_pieces_count=today_pieces_count,
                           today_collections_count=today_collections_count)


@bp.route('/admin/users')
@AdminPermission()
def users():
    users = User.query.order_by(User.created_at.desc())
    return render_template('admin/users.html', users=users)


@bp.route('/admin/report_piece_logs', methods=['GET', 'POST'])
@AdminPermission()
def piece_log_reports():
    """管理句子恶意编辑举报"""
    reports = PieceEditLogReport.query
    return render_template('admin/piece_log_reports.html', reports=reports)


@bp.route('/admin/piece_log_report/<int:uid>/process')
@AdminPermission()
def process_piece_log_report(uid):
    """处理句子恶意编辑举报"""
    report = PieceEditLogReport.query.get_or_404(uid)
    report.processed = True
    db.session.add(report)
    db.session.commit()
    return redirect(request.referrer or url_for('.piece_log_reports'))


@bp.route('/admin/report_collection_logs', methods=['GET', 'POST'])
@AdminPermission()
def collection_log_reports():
    """管理句集恶意编辑举报"""
    reports = CollectionEditLogReport.query
    return render_template('admin/collection_log_reports.html', reports=reports)


@bp.route('/admin/collection_log_report/<int:uid>/process')
@AdminPermission()
def process_collection_log_report(uid):
    """处理句集恶意编辑举报"""
    report = CollectionEditLogReport.query.get_or_404(uid)
    report.processed = True
    db.session.add(report)
    db.session.commit()
    return redirect(request.referrer or url_for('.collection_log_reports'))


@bp.route('/admin/feedback', methods=['GET', 'POST'])
@AdminPermission()
def feedback():
    """管理意见反馈"""
    feedbacks = Feedback.query
    return render_template('admin/feedback.html', feedbacks=feedbacks)


@bp.route('/admin/feedback/<int:uid>/process')
@AdminPermission()
def process_feedback(uid):
    """处理这一条意见反馈"""
    feedback = Feedback.query.get_or_404(uid)
    feedback.processed = True
    db.session.add(feedback)
    db.session.commit()
    return redirect(request.referrer or url_for('.feedback'))


@bp.route('/invitation', defaults={'page': 1}, methods=['GET', 'POST'])
@bp.route('/invitation/page/<int:page>', methods=['GET', 'POST'])
@AdminPermission()
def invitation(page):
    """注册码管理"""
    codes = InvitationCode.query.order_by(InvitationCode.created_at.desc()).paginate(page, 15)
    return render_template('admin/invitation.html', codes=codes)


@bp.route('/generate_invitation_codes')
@AdminPermission()
def generate_invitation_codes():
    """生成注册码"""
    for i in xrange(0, 10):
        code = InvitationCode(code=gen_salt(16))
        db.session.add(code)
    db.session.commit()
    return redirect(request.referrer)


@bp.route('/invitation_code/<int:uid>/send', methods=['GET', 'POST'])
@AdminPermission()
def send_invitation_code(uid):
    """向用户邮箱发送邀请码"""
    invitation_code = InvitationCode.query.get_or_404(uid)
    if invitation_code.email or invitation_code.used:
        flash('该邀请码无法使用')
        return redirect(url_for('.invitation'))

    form = SendInvitationCodeForm(code=invitation_code.code)
    if form.validate_on_submit():
        if send_invitation_mail(form.email.data, invitation_code.code):
            invitation_code.email = form.email.data
            invitation_code.sended_at = datetime.datetime.now()
            invitation_code.sender_id = g.user.id
            db.session.add(invitation_code)
            db.session.commit()
            flash('发送成功')
        else:
            flash('发送失败')
        return redirect(url_for('.invitation'))
    return render_template('admin/send_invitation_code.html', form=form,
                           invitation_code=invitation_code)

application/templates/layout.html
<!doctype html>
<html id="{{ page_id(self) }}">
<head>
   <title>{% block page_title %}{% endblock %}</title>
   <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
   <meta name="renderer" content="webkit">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="csrf-token" content="{{ csrf_token() }}"/>
   {% block meta %}{% endblock %}
   <link rel="Shortcut Icon" href="{{ static('image/favicon.ico') }}">
   <link rel="apple-touch-icon-precomposed" sizes="152x152"
         href="{{ static('image/apple/apple-touch-icon-precomposed-152.png') }}">
   <link rel="apple-touch-icon-precomposed" sizes="120x120"
         href="{{ static('image/apple/apple-touch-icon-precomposed-120.png') }}">
   <link rel="apple-touch-icon-precomposed" sizes="76x76"
         href="{{ static('image/apple/apple-touch-icon-precomposed-76.png') }}">
   <link rel="apple-touch-icon-precomposed"
         href="{{ static('image/apple/apple-touch-icon-precomposed.png') }}">
   {{ app_css(self) }}
   <!--[if IE 9]>
   <link rel="stylesheet" href="{{ static('css/ie9.css') }}"/>
   <![endif]-->
   <!--[if IE 8]>
   <link rel="stylesheet" href="{{ static('css/ie8.css') }}"/>
   <![endif]-->
   <script type="text/javascript">
      var g = {
         rules: {{ rules|safe }},
         domain: "{{ config.SITE_DOMAIN }}",
         csrfToken: "{{ csrf_token() }}",
         method: "{{ request.method }}",
         signedIn: {% if g.user %}true{% else %}false{% endif %},
         pluploadDefaults: {
            flash_swf_url: '/static/bower_components/plupload/js/Moxie.swf',
            silverlight_xap_url: '/static/bower_components/plupload/js/Moxie.xap'
         },
         timerForBackdrop: null
      };
   </script>
   {{ libs_js() }}

   {# Access analysis #}
   <script>
      var _hmt = _hmt || [];
      (function () {
         var hm = document.createElement("script");
         hm.src = "//hm.baidu.com/hm.js?92bb32739ba6cda8b515505ad55a9d1d";
         var s = document.getElementsByTagName("script")[0];
         s.parentNode.insertBefore(hm, s);
      })();
   </script>
</head>

<body>
<div id="favicon-wx-share" style="margin: 0; display: none;">
   <img src="{{ static('image/favicon_wx_share.png') }}" alt=""/>
</div>
<div class="base-wap">
   {# Flash message #}
   {% with message = get_flashed_messages()[0] %}
      {% if message %}
         <div class="alert alert-info flash-message">{{ message }}</div>
      {% endif %}
   {% endwith %}

   <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('site.index') }}">
               <img src="{{ static('image/1jingdian.png') }}" alt=""/>
               <small>每天分享好句子</small>
            </a>
         </div>

         <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
               <li>
                  <a href="{{ url_for('piece.add') }}" class="need-signed-in">
                     <span class="fa fa-plus"></span> 分享句子
                  </a>
                  {#                  {% if not g.user or permissions.PieceAddPermission().check() %}#}
                  {#                     <a href="{{ url_for('piece.add') }}" class="need-signed-in">#}
                  {#                        <span class="fa fa-plus"></span> 分享句子#}
                  {#                     </a>#}
                  {#                  {% else %}#}
                  {#                     <a title="今日已分享 2 个句子" class="disabled">#}
                  {#                        <span class="fa fa-plus"></span> 分享句子#}
                  {#                     </a>#}
                  {#                  {% endif %}#}
               </li>

               {#            <li>#}
               {#               <a href="{{ url_for('site.search') }}">#}
               {#                  <span class="fa fa-search"></span> 搜索#}
               {#               </a>#}
               {#            </li>#}

               <li>
                  <a href="javascript:void(0)" class="btn-meet">偶遇</a>
               </li>

               <li>
                  <a href="{{ url_for('site.collections') }}">句集</a>
               </li>

               {% if g.user %}
                  <li>
                     <a href="{{ url_for('user.notifications') }}">
                        通知
                        {% if notifications_count %}
                           <span class="notifications-count">{{ notifications_count }}</span>
                        {% endif %}
                     </a>
                  </li>

                  {% if permissions.AdminPermission().check() %}
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           管理 <span class="fa fa-angle-down"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                           <li><a href="{{ url_for('admin.dashboard') }}">Dashboard</a></li>
                           <li><a href="{{ url_for('admin.users') }}">用户管理</a></li>
                           <li><a href="{{ url_for('admin.invitation') }}">邀请码</a></li>
                           <li><a href="{{ url_for('admin.feedback') }}">意见反馈</a></li>
                           <li>
                              <a href="{{ url_for('admin.piece_log_reports') }}">
                                 句子恶意编辑
                              </a>
                           </li>
                           <li>
                              <a href="{{ url_for('admin.collection_log_reports') }}">
                                 句集恶意编辑
                              </a>
                           </li>
                        </ul>
                     </li>
                  {% endif %}

                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {{ g.user.name }} <span class="fa fa-angle-down"></span>
                     </a>
                     <ul class="dropdown-menu" role="menu">
                        <li><a href="{{ url_for('user.profile', uid=g.user.id) }}">个人主页</a></li>
                        <li><a href="{{ url_for('user.likes', uid=g.user.id) }}">我的收藏</a></li>
                        <li><a href="{{ url_for('feedback.add') }}">意见反馈</a></li>
                        <li><a href="{{ url_for('user.settings') }}">设置</a></li>
                        <li><a href="{{ url_for('account.signout') }}">登出</a></li>
                     </ul>
                  </li>
               {% else %}
                  <li>
                     <a href="{{ url_for('account.signin') }}" id="nav-signin">登录</a>
                     <span class="nav-devider hidden-xs">/</span>
                     <a href="{{ url_for('account.signup') }}" id="nav-signup">注册</a>
                  </li>
               {% endif %}
            </ul>
         </div>
      </div>
   </nav>

   <div id="main-wap">
      {% block page_content %}{% endblock %}
   </div>

   <div id="footer">
      <ul id='links' class="list-unstyled list-inline">
         <li class="copyright">© 2015</li>
         <li><a href="{{ url_for('site.about') }}">关于</a></li>
         <li><a href="http://blog.1jingdian.com/" target="_blank">博客</a></li>
         <li><a href="https://github.com/1jingdian" target="_blank">GitHub</a></li>
      </ul>
   </div>
</div>

{# Inject vars on g for single page #}
{% block page_vars %}{% endblock %}

{{ page_js(self) }}
</body>
</html>